[2024-08-05T16:41:10.723+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T16:41:10.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-08-05T16:41:00.565998+00:00 [queued]>
[2024-08-05T16:41:10.740+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-08-05T16:41:00.565998+00:00 [queued]>
[2024-08-05T16:41:10.740+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-05T16:41:10.862+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-08-05 16:41:00.565998+00:00
[2024-08-05T16:41:10.868+0000] {standard_task_runner.py:64} INFO - Started process 24993 to run task
[2024-08-05T16:41:10.872+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-08-05T16:41:00.565998+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpmnmoa58i']
[2024-08-05T16:41:10.872+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask transform_load_weather_data
[2024-08-05T16:41:10.914+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-08-05T16:41:00.565998+00:00 [running]> on host ip-172-31-17-139.us-east-2.compute.internal
[2024-08-05T16:41:10.976+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T16:41:00.565998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T16:41:00.565998+00:00'
[2024-08-05T16:41:10.977+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T16:41:10.990+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-08-05T16:41:11.008+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2024-08-05T16:41:11.260+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T16:41:11.260+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T16:41:11.265+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-08-05T16:41:00.565998+00:00, execution_date=20240805T164100, start_date=20240805T164110, end_date=20240805T164111
[2024-08-05T16:41:11.324+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T16:41:11.337+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T16:41:11.337+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
