[2024-08-05T15:47:21.428+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T15:47:21.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2024-08-05T15:47:15.128506+00:00 [queued]>
[2024-08-05T15:47:21.444+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2024-08-05T15:47:15.128506+00:00 [queued]>
[2024-08-05T15:47:21.445+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-05T15:47:21.564+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2024-08-05 15:47:15.128506+00:00
[2024-08-05T15:47:21.570+0000] {standard_task_runner.py:64} INFO - Started process 20606 to run task
[2024-08-05T15:47:21.575+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2024-08-05T15:47:15.128506+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp9pg96kol']
[2024-08-05T15:47:21.575+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask is_weather_api_ready
[2024-08-05T15:47:21.615+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2024-08-05T15:47:15.128506+00:00 [running]> on host ip-172-31-17-139.us-east-2.compute.internal
[2024-08-05T15:47:21.676+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T15:47:15.128506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T15:47:15.128506+00:00'
[2024-08-05T15:47:21.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T15:47:21.677+0000] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-08-05T15:47:21.678+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Portland&APPID=db97ffbdec6d489dc0c7e095e650136a
[2024-08-05T15:47:21.682+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-08-05T15:47:21.727+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-08-05T15:47:21.727+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T15:47:21.733+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=manual__2024-08-05T15:47:15.128506+00:00, execution_date=20240805T154715, start_date=20240805T154721, end_date=20240805T154721
[2024-08-05T15:47:21.785+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T15:47:21.809+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T15:47:21.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
